//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.TransaksiDetail = new HashSet<TransaksiDetail>();
        }
    
        public int InventoryID { get; set; }
        public string NamaItem { get; set; }
        public string Deskripsi { get; set; }
        public decimal Harga { get; set; }
        public int Stok { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaksiDetail> TransaksiDetail { get; set; }
    }
}
