//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaksi()
        {
            this.TransaksiDetail = new HashSet<TransaksiDetail>();
        }
    
        public int TransaksiID { get; set; }
        public System.DateTime TanggalTransaksi { get; set; }
        public Nullable<int> UserID { get; set; }
        public decimal Total { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaksiDetail> TransaksiDetail { get; set; }
        public virtual User User { get; set; }
    }
}
